services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_APP: "app.py"
      FLASK_DEBUG: "true"
      FLASK_RUN_HOST: "0.0.0.0"

  redis:
    image: "redis:alpine"
